sudo: required

addons:
  apt:
    update: true

language: generic

branches:
  only:
  - master

services:
  - docker

before_script:
  - ./cli.sh travis_setup
  - ./cli.sh init

script:
  - ./cli.sh build
